// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbIk7HCsK6QekmD5byOc_ZcrT0bm-CZjg',
    appId: '1:423347789169:web:a396eb2dc21ef7e34eaad0',
    messagingSenderId: '423347789169',
    projectId: 'my-yoga-app-sanctuary',
    authDomain: 'my-yoga-app-sanctuary.firebaseapp.com',
    storageBucket: 'my-yoga-app-sanctuary.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0bqhO3-VowsEnsCDwamGI1B1UFtXc__0',
    appId: '1:423347789169:android:83a78458181bcf584eaad0',
    messagingSenderId: '423347789169',
    projectId: 'my-yoga-app-sanctuary',
    storageBucket: 'my-yoga-app-sanctuary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBshaOtS-jVXGweeNdF2H6JFvTrZ9LtqWo',
    appId: '1:423347789169:ios:cd14b50b5e09063a4eaad0',
    messagingSenderId: '423347789169',
    projectId: 'my-yoga-app-sanctuary',
    storageBucket: 'my-yoga-app-sanctuary.firebasestorage.app',
    iosBundleId: 'com.example.antigravity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBshaOtS-jVXGweeNdF2H6JFvTrZ9LtqWo',
    appId: '1:423347789169:ios:cd14b50b5e09063a4eaad0',
    messagingSenderId: '423347789169',
    projectId: 'my-yoga-app-sanctuary',
    storageBucket: 'my-yoga-app-sanctuary.firebasestorage.app',
    iosBundleId: 'com.example.antigravity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbIk7HCsK6QekmD5byOc_ZcrT0bm-CZjg',
    appId: '1:423347789169:web:a765d99f34b24b404eaad0',
    messagingSenderId: '423347789169',
    projectId: 'my-yoga-app-sanctuary',
    authDomain: 'my-yoga-app-sanctuary.firebaseapp.com',
    storageBucket: 'my-yoga-app-sanctuary.firebasestorage.app',
  );
}
